server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: bet-service
          uri: http://localhost:8082
          predicates:
            - Path=/bet/**